version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/golang
hook:
  BeforeInstall:
    - location: codedeploy/BeforeInstall.sh
  AfterInstall:
    - location: codedeploy/AfterInstall.sh
  ApplicationStop:
    - location: codedeploy/ApplicationStop.sh
  ApplicationStart:
    - location: codedeploy/ApplicationStart.sh
  ValidateService:
    - location: codedeploy/ValidateService.sh  
